---
title: "pam_code"
author: "Hayden Vega"
date: "2024-10-09"
output: html_document
---
```{r}
devtools::install_github("an-bui/calecopal")
install.packages("installr")
install.packages("viridis")
```

```{r setup, include=FALSE}
library(janitor)
library(tidyverse)
library(viridis)
library(lme4)
library(ggeffects)
library(sjlabelled)
library(DHARMa)
library(parameters)
library(effects)
library(MuMIn)
```

## Load in Data
```{r}

pam_healed <- read.csv("pam_healed.csv", header = TRUE, sep = ",")

pam_undisturbed_healed <- read.csv("pam_undisturbed_healed.csv", header = TRUE, sep = ",")

```


## Boxplot of Pam for undisturbed tissue
```{r}


pam_undisturbed_healed %>% 
  ggplot(aes (x = fish, y = fv_fm, fill = fish)) +
  geom_boxplot()+
  theme_bw()

  ## Boxplot of PAM including x = wound and  fish = fill
pam_undisturbed_healed %>% 
  ggplot (aes (x = wound, y = fv_fm, fill = fish))+
  geom_boxplot()+
  theme_bw()

  ## Boxplot of PAM including x = fish and fill = wound

pam_undisturbed_healed %>% 
  ggplot (aes (x = fish, y = fv_fm, fill = wound))+
  geom_boxplot()+
  theme_bw()

pam_undisturbed_healed %>% 
  ggplot (aes (x = wound, y = fv_fm, fill = wound))+
  geom_boxplot()+
  theme_bw()

```


## Boxplot of PAM for healed tissue
```{r}
pam_healed %>% 
  ggplot(aes (x = fish, y = fv_fm, fill = fish)) +
  geom_boxplot()+
  theme_bw()

pam_healed %>% 
  ggplot(aes (x = fish, y = fv_fm, fill = wound)) +
  geom_boxplot()+
  theme_bw()

pam_healed %>% 
  ggplot(aes (x = wound, y = fv_fm, fill = wound)) +
  geom_boxplot()+
  theme_bw()

pam_healed %>% 
  ggplot(aes (x = wound, y = fv_fm, fill = fish)) +
  geom_boxplot()+
  theme_bw()






```


#Multiple Regression

```{r}
pam_all_regression <- lmer(fv_fm ~ wound * fish + (1 | f0), data = pam_undisturbed_healed)
summary(pam_all_regression)
anova(pam_all_regression)

pam_healed_regression <- lmer(fv_fm ~ wound + fish + (1 | f0), data = pam_healed)
summary(pam_healed_regression)
anova(pam_healed_regression)
```

#Anova
```{r}
pam_all_anova <- aov(fv_fm ~ wound * fish, data = pam_undisturbed_healed)

summary(pam_all_anova)

pam_healed_anova <- aov(fv_fm ~ wound * fish, data = pam_healed)
```
#Tukey
```{r}
pam_all_tukey <- TukeyHSD(pam_all_anova)
pam_all_tukey

pam_healed_tukey <- TukeyHSD(pam_healed_anova)
pam_healed_tukey
```


#R2 values
```{r}

MuMIn::r.squaredGLMM(pam_all_regression)

MuMIn::r.squaredGLMM(pam_healed_regression)
```

```{r}
pam_all_predictions <- ggpredict(pam_all_regression, terms = c("wound", "fish")) %>% 
  as_tibble() %>% 
  rename(wound = group)
```

#Visualize pam_all
```{r}
pam_all_plot <- ggplot() +
  
  # plot the raw data as points
  geom_point(data = pam_undisturbed_healed,
             aes(x = wound,
                 y = fv_fm),
             alpha = 0.5,
             color = "black",
             shape = 21) +
  
  # plot a 1:1 reference line
 # geom_abline(slope = 1, 
  #            intercept = 0,
   #           linetype = 2,
    #          linewidth = 1,
     #         color = "black") +
  
  # plot the confidence interval 
 # geom_ribbon(data = pam_all_predictions,
  #            aes(x = x,
   #               y = predicted,
    #              ymin = conf.low,
     #             ymax = conf.high),
      #        alpha = 0.2,
       #       fill = "black") +
  
  # plot the prediction line
#  geom_line(data = pam_all_predictions,
 #           aes(x = x,
  #              y = predicted),
   #         color = "black",
    #        linewidth = 1) +
  
  # labels
  labs(x = "Wound Intensity",
       y = "Photosynthetic Efficiency") 

pam_all_plot

```

#Plot TUKEY

```{r  fig.width = 20, fig.height = 40}
tukey_plot_all <- aov(fv_fm ~ wound:fish, data = pam_undisturbed_healed)

tukey_plot_all_plot <- TukeyHSD(tukey_plot_all)
plot(tukey_plot_all_plot)


tukey_plot_healed <- aov(fv_fm~wound:fish, data = pam_healed)

tukey_healed <- TukeyHSD(tukey_plot_healed)
plot(tukey_healed)

#Seems that large: no fish is significantly different from small and large with fish; suggests that as wound size increases (high metabolic stress) fish effects emerge. within treatments with fish did not vary. and treatments within small wounds did not vary significantly from each other. #supports positive gradient hypothesis #IS THIS SUPPORTED BY BUOYANT WEIGHT DATA?
```
#RANDOMIZATION TEST ARGHHHH
```{r}
#PAM first
#looking at the mean between wounds



#Actually randomize
null_photo_dist <- replicate(1000, {
  photo_means <- pam_healed %>% 
    mutate(wound = sample(wound, n())) %>% #this shuffles the selection of data
  group_by(wound) %>% 
  summarize(mean = mean(fv_fm))

 diff_means <- photo_means$mean[2]-
  photo_means$mean[1]
 
 diff_means
})

ggplot(tibble(null_photo_dist), aes(null_photo_dist)) +
  geom_histogram(bins = 20, 
                 color = "cornflowerblue", 
                 fill = NA)+
  geom_vline(xintercept = diff_means, 
             color = "firebrick")


```
#Means between fish within wounds
```{r}
large <- pam_healed %>% 
  filter(wound == "Large")

photo_means <- large %>% 
  group_by(fish) %>% 
  summarize(mean = mean(fv_fm))

#Actually randomize
nulll_photo_dist <- replicate(1000, {
  photo_means <- large %>% 
    mutate(fish = sample(fish, n())) %>% #this shuffles the selection of data
  group_by(fish) %>% 
  summarize(mean = mean(fv_fm))

 diff_means <- photo_means$mean[2]- 1.09*photo_means$mean[1]
 
 diff_means
})

ggplot(tibble(nulll_photo_dist), aes(nulll_photo_dist)) +
  geom_histogram(bins = 20, 
                 color = "cornflowerblue", 
                 fill = NA)+
  geom_vline(xintercept = diff_means, 
             color = "firebrick")
```
#do it for small wounds
```{r}
small <- pam_healed %>% 
  filter(wound == "Small")

photo_means <- small %>% 
  group_by(fish) %>% 
  summarize(mean = mean(fv_fm))

#Actually randomize
nullll_photo_dist <- replicate(1000, {
  photo_means <- small %>% 
    mutate(fish = sample(fish, n())) %>% #this shuffles the selection of data
  group_by(fish) %>% 
  summarize(mean = mean(fv_fm))

 diff_means <- photo_means$mean[2] - photo_means$mean[1]
 
 diff_means
})

ggplot(tibble(nullll_photo_dist), aes(nullll_photo_dist)) +
  geom_histogram(bins = 20, 
                 color = "cornflowerblue", 
                 fill = NA)+
  geom_vline(xintercept = diff_means, 
             color = "firebrick")

```



#Do it for growth
```{r}
buoy_data <- read.csv("fish_regen_buoyantweight (1).csv")
```

```{r}
null_growth_dist <- replicate(1000, {
  photo_means <- small %>% 
    mutate(fish = sample(fish, n())) %>% #this shuffles the selection of data
  group_by(fish) %>% 
  summarize(mean = mean(fv_fm))

 diff_means <- photo_means$mean[2] - photo_means$mean[1]
 
 diff_means
})

ggplot(tibble(nullll_photo_dist), aes(nullll_photo_dist)) +
  geom_histogram(bins = 20, 
                 color = "cornflowerblue", 
                 fill = NA)+
  geom_vline(xintercept = diff_means, 
             color = "firebrick")
```

#something New
```{r}
null_photo_dist <- replicate(1000, {
  photo_means <- pam_healed %>%
    mutate(wound = sample(wound, n()), #this shuffles the selection of data
                     fish_presence = sample(fish, n())) %>% #this shuffles the selection of for fish presence
  group_by(wound) %>%
  summarize(mean = mean(fv_fm))

 diff_means <- photo_means$mean[2]-
  photo_means$mean[1]

 diff_means
})

ggplot(tibble(null_photo_dist), aes(null_photo_dist)) +
  geom_histogram(bins = 20,
                 color = "cornflowerblue",
                 fill = NA)+
  geom_vline(xintercept = diff_means,
             color = "firebrick")
```

